version: "3"
services:
  flask-mysql:
    container_name: flask-mysql
    build: ./mysql
    volumes:
      - ./mysql/volume:/var/lib/mysql
    ports:
      - 33061:3306
    networks:
      - flask

networks:
  flask: